{
    Throwable exception;
    log ("a string" +exception);
    carryOn();
}